//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_API_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Users1 = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string EmailId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> AccountCreatedDate { get; set; }
        public Nullable<int> LoginAttempt { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SalutationId { get; set; }
        public string MiddleName { get; set; }
        public string MD { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> mailingdate { get; set; }
        public Nullable<int> MailingAddressId { get; set; }
        public bool MarkForPrinting { get; set; }
        public string Comments { get; set; }
        public bool Resume { get; set; }
        public Nullable<System.DateTime> HiringStartDate { get; set; }
        public Nullable<System.DateTime> HiringEndDate { get; set; }
        public bool HIPAATraining { get; set; }
        public bool CORI { get; set; }
        public Nullable<System.DateTime> CoriExpiry { get; set; }
        public bool ESORI { get; set; }
        public Nullable<System.DateTime> EsoriExpiry { get; set; }
        public bool FraudCheck { get; set; }
        public string Notes { get; set; }
        public string InterpreterNo { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> IsText { get; set; }
        public Nullable<bool> IsEmail { get; set; }
        public Nullable<bool> IsEligibleToReturn { get; set; }
        public string HomeAddress { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string InterpreterStatus { get; set; }
        public Nullable<int> CredentialId { get; set; }
        public Nullable<int> Zip { get; set; }
        public string ResumeFilePath { get; set; }
        public string FileName { get; set; }
        public string RolesWithCCCS { get; set; }
        public string FormOfTransportations { get; set; }
        public Nullable<int> InterpreterStatusId { get; set; }
        public Nullable<int> OrganizationsId { get; set; }
        public string CredentialLst { get; set; }
        public bool Car { get; set; }
        public bool PublicTransport { get; set; }
        public Nullable<int> VendorContactId { get; set; }
        public Nullable<int> StudentCategoryId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public string LinkedUsers { get; set; }
    
        public virtual ICollection<User> Users1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
